### ISSUE TITLE
automatically 

### ISSUE THREAD

**Issue by FreeVB** [FatRainbowPony/Dock-window#1]
When you publish as a single file, it cannot be automatically hidden

**Comment by FatRainbowPony** [comment]
@FreeVB, I didn't quite understand what you were talking about

**Comment by FreeVB** [comment]
What I mean by this is that when the project is published as a single file, the auto-hide feature will not be available when the EXE runtime is opened.

**Comment by FatRainbowPony** [comment]
@FreeVB, in which release did you see this problem?

**Comment by FreeVB** [comment]
The latest downloaded source code is compiled

**Comment by FatRainbowPony** [comment]
@FreeVB, I'll try to fix it soon

**Comment by FatRainbowPony** [comment]
@FreeVB, try using test assembly from [DockWindow.zip](https://github.com/user-attachments/files/16829375/DockWindow.zip) and say to me about result

**Comment by FreeVB** [comment]
No problem, using this DLL can test successfully normally.

**Comment by FatRainbowPony** [comment]
Good, then I'm making a new release and closing this issue
