### ISSUE TITLE
The solution does not compile

### ISSUE THREAD

**Issue by ivanvoyager** [FatRainbowPony/Dock-window#2]
Can't find assets.

**Comment by FatRainbowPony** [comment]
@IvanGit, if you are having problems compiling the solution, then you should remove the references to Icon.png and README.md from the Dock window project. These files are only needed to create a NuGet package

**Comment by FatRainbowPony** [comment]
@IvanGit, I have updated the source code of the project, adding the references to assets, for easy compilation of solution. Try the current version of the source code
